dist: focal

language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-9
      - g++-9

script:
  # Link gcc-9 and g++-9 to their standard commands
  - ln -s /usr/bin/gcc-9 /usr/local/bin/gcc
  - ln -s /usr/bin/g++-9 /usr/local/bin/g++
  # Export CC and CXX to tell cmake which compiler to use
  - export CC=/usr/bin/gcc-9
  - export CXX=/usr/bin/g++-9
  - make
