os: linux
dist: bionic

language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-9
      - g++-9

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    export CC=gcc-9 ;
    export CXX=g++-9 ;
  fimake
  - make
