version: "3.9"
services:
  lbt_docker:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true # Docker run -i
    tty: true        # Docker run -t
    volumes: # Mount relevant folders into container
      - ./.vscode:/code/lbt/.vscode # Necessary for using VS Code Tasks inside container
      - ./src:/code/lbt/src
      - ./tests:/code/lbt/tests
      - ./examples:/code/lbt/examples
