version: "3.9"
services:
  lbt_docker:
    extends:
      file: docker-compose.yml
      service: lbt_docker
    environment:
     - NVIDIA_VISIBLE_DEVICES=all
     - QT_X11_NO_MITSHM=1
    runtime: nvidia
