name: Trigger tests

on:
  push:
    paths:
      - 'include/**'
      - 'src/**'
      - 'test/**'
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger run-tests workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: ${{ github.repository }}
          event-type: trigger-tests

